#!/bin/bash
#
# AgentRQ Quick Setup Script
# Generates required secrets and creates .env file
#
# Usage: ./scripts/setup.sh [local|production]
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         AgentRQ Setup Assistant                             ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Determine environment
ENV_TYPE="${1:-local}"

if [[ "$ENV_TYPE" != "local" && "$ENV_TYPE" != "production" ]]; then
    echo -e "${RED}Error: Invalid environment. Use 'local' or 'production'${NC}"
    echo "Usage: ./scripts/setup.sh [local|production]"
    exit 1
fi

echo -e "${YELLOW}Setting up for: $ENV_TYPE environment${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠  .env file already exists${NC}"
    read -p "Overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 1
    fi
fi

# Generate secrets
echo -e "${GREEN}✓ Generating secrets...${NC}"
JWT_SECRET=$(openssl rand -base64 32)
TOKEN_KEY=$(openssl rand -hex 16)  # 32 bytes

echo -e "${GREEN}✓ Secrets generated${NC}"
echo ""

# Collect user input
echo -e "${YELLOW}Configure Authentication${NC}"
read -p "Google OAuth Client ID: " GOOGLE_CLIENT_ID
read -sp "Google OAuth Client Secret: " GOOGLE_CLIENT_SECRET
echo

if [ "$ENV_TYPE" = "production" ]; then
    echo ""
    echo -e "${YELLOW}Configure Production Environment${NC}"
    read -p "Domain (e.g., agentrq.mycompany.com): " DOMAIN
    read -p "Email for Let's Encrypt: " LE_EMAIL
else
    DOMAIN="localhost"
    LE_EMAIL=""
fi

echo ""
echo -e "${YELLOW}Optional: Slack Integration${NC}"
read -p "Enable Slack? (y/N) " -n 1 -r
echo

ENABLE_SLACK=false
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ENABLE_SLACK=true
    read -p "Slack Client ID: " SLACK_CLIENT_ID
    read -sp "Slack Client Secret: " SLACK_CLIENT_SECRET
    echo
    read -p "Slack Signing Secret: " SLACK_SIGNING_SECRET
    read -p "Slack App ID: " SLACK_APP_ID
fi

echo ""
echo -e "${YELLOW}Optional: PostgreSQL Database${NC}"
read -p "Use PostgreSQL? (y/N) " -n 1 -r
echo

USE_POSTGRES=false
if [[ $REPLY =~ ^[Yy]$ ]]; then
    USE_POSTGRES=true
    read -p "PostgreSQL Host (default: localhost): " -e PG_HOST
    PG_HOST=${PG_HOST:-localhost}
    read -p "PostgreSQL Port (default: 5432): " -e PG_PORT
    PG_PORT=${PG_PORT:-5432}
    read -p "PostgreSQL User (default: postgres): " -e PG_USER
    PG_USER=${PG_USER:-postgres}
    read -sp "PostgreSQL Password: " PG_PASSWORD
    echo
fi

# Determine base URL
if [ "$ENV_TYPE" = "production" ]; then
    BASE_URL="https://$DOMAIN"
    SSL_ENABLED="true"
    PORT="80"
else
    BASE_URL="http://localhost:2026"
    SSL_ENABLED="false"
    PORT="2026"
fi

# Generate .env file
echo ""
echo -e "${GREEN}✓ Generating .env file...${NC}"

cat > .env << EOF
# Generated by setup.sh on $(date)

# Environment
ENV=$ENV_TYPE
PORT=$PORT
AGENTRQ_BASE_URL=$BASE_URL
AGENTRQ_DOMAIN=$DOMAIN

# Authentication
AGENTRQ_AUTH_JWT_SECRET=$JWT_SECRET
AGENTRQ_AUTH_WORKSPACE_TOKEN_KEY=$TOKEN_KEY
AGENTRQ_AUTH_ROOT_LOGIN_ENABLED=false
AGENTRQ_AUTH_ROOT_ACCESS_TOKEN=

# Google OAuth
AGENTRQ_ACCOUNTS_OAUTH2_CLI_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
AGENTRQ_ACCOUNTS_OAUTH2_CLI_GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

# TLS
AGENTRQ_SSL_ENABLED=$SSL_ENABLED
AGENTRQ_SSL_LETSENCRYPT_EMAIL=$LE_EMAIL
AGENTRQ_SSL_CACHE_DIR=/_certs

# Database
AGENTRQ_SQLITE_ENABLED=$([ "$USE_POSTGRES" = "true" ] && echo "false" || echo "true")
AGENTRQ_SQLITE_DSN=./storage/agentrq.db

AGENTRQ_POSTGRES_ENABLED=$([ "$USE_POSTGRES" = "true" ] && echo "true" || echo "false")
AGENTRQ_POSTGRES_HOST=$PG_HOST
AGENTRQ_POSTGRES_PORT=$PG_PORT
AGENTRQ_POSTGRES_USER=$PG_USER
AGENTRQ_POSTGRES_PASSWORD=$PG_PASSWORD
AGENTRQ_POSTGRES_DBNAME=agentrq

# Slack Integration
AGENTRQ_SLACK_ENABLED=$([ "$ENABLE_SLACK" = "true" ] && echo "true" || echo "false")
AGENTRQ_SLACK_CLIENT_ID=$SLACK_CLIENT_ID
AGENTRQ_SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET
AGENTRQ_SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
AGENTRQ_SLACK_APP_ID=$SLACK_APP_ID

# Email
AGENTRQ_SMTP_ENABLED=false
AGENTRQ_SMTP_HOST=
AGENTRQ_SMTP_PORT=587

# Security
AGENTRQ_DDOS_ENABLED=true
AGENTRQ_RATELIMIT_ENABLED=true
EOF

echo -e "${GREEN}✓ .env file created${NC}"
echo ""

# Create storage directory
echo -e "${GREEN}✓ Creating storage directory...${NC}"
mkdir -p storage
chmod 0777 storage

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                  Setup Complete!                            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [ "$ENV_TYPE" = "local" ]; then
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Start with Docker Compose:"
    echo -e "     ${GREEN}docker-compose up -d${NC}"
    echo ""
    echo "  2. Open your browser:"
    echo -e "     ${GREEN}http://localhost:2026${NC}"
    echo ""
    echo "  3. Sign in with Google OAuth"
else
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Verify .env file and adjust as needed"
    echo "  2. Start with Docker Compose:"
    echo -e "     ${GREEN}docker-compose up -d${NC}"
    echo ""
    echo "  3. Wait for Let's Encrypt certificate provisioning"
    echo "  4. Visit: https://$DOMAIN"
fi

echo ""
echo "View logs: docker-compose logs -f agentrq"
echo ""
